# fly.toml file generated for art-expert-excited-newbeez-test on 2023-04-14T20:17:25+03:00

app = "art-expert-excited-newbeez-test"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lax"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
