name: Deploy services to FLY IO 
on:
  push:
    branches:
      - main
jobs:
  deploy-fastapi:
    name: Deploy FastAPI 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fastapi-service
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install dependencies and mlem build
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel
        pip install "mlem[streamlit,flyio]"
        pip install -r requirements.txt
        mlem build docker_dir -m ./models/price_keras_preprocess --target dockerdir --file_conf server=server.mlem
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy to FLY IO
      working-directory: ./fastapi-service/dockerdir
      run: |
        flyctl deploy --remote-only -a art-expert-excited-newbeez
        flyctl scale memory 2048
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-bot:
    needs: deploy-fastapi
    name: Deploy TelegramBot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to FLY IO
        run: |
          flyctl secrets set TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          flyctl deploy --remote-only -a art-expert-excited-newbeez-bot
          flyctl scale memory 512
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
